#!/usr/bin/env python3
"""
renamee_revert.py

根据 renamee_new.py 生成的 rename_log.csv，将文件移回原始位置。
支持部分回溯（中途崩溃的情况）：只回溯 CSV 中记录的已完成移动。

Usage:
  python renamee_revert.py --csv "D:\\data\\pet_output\\2000000000\\2e9\\rename_log.csv"
"""

import os
import shutil
import argparse
import csv


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--csv', type=str, required=True,
                        help='Path to rename_log.csv generated by renamee_new.py')
    parser.add_argument('--dry_run', action='store_true',
                        help='Print what would be done without actually moving files')
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f"ERROR: CSV not found: {args.csv}")
        return

    with open(args.csv, 'r', encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    print(f"Read {len(rows)} entries from {args.csv}")
    if args.dry_run:
        print("DRY RUN mode — no files will be moved\n")

    ok = 0
    skipped = 0
    errors = 0

    for row in rows:
        src = row['src']   # 原始路径（要还原到这里）
        dst = row['dst']   # 当前路径（文件现在在这里）

        if not os.path.exists(dst):
            print(f"  [SKIP] dst not found (already reverted?): {dst}")
            skipped += 1
            continue

        if os.path.exists(src):
            print(f"  [SKIP] src already exists, won't overwrite: {src}")
            skipped += 1
            continue

        # 确保原始目录存在
        src_dir = os.path.dirname(src)
        if not args.dry_run:
            os.makedirs(src_dir, exist_ok=True)

        print(f"  {'[DRY]' if args.dry_run else ''} {dst}  →  {src}")

        if not args.dry_run:
            try:
                shutil.move(dst, src)
                ok += 1
            except Exception as e:
                print(f"    ERROR: {e}")
                errors += 1
        else:
            ok += 1

    print(f"\nDone. moved={ok}, skipped={skipped}, errors={errors}")
    if not args.dry_run and ok > 0:
        print("Files have been restored to original locations.")


if __name__ == '__main__':
    main()
